version: '3.8'
services:
  backend:
    build: ./backend
    container_name: hotel-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: hotel-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
